# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('category', models.CharField(max_length=30)),
                ('thumbnail_url', models.URLField()),
                ('mesh_url', models.URLField()),
            ],
        ),
    ]
