# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='mesh_url',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='asset',
            name='mesh',
            field=models.FileField(default=None, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='thumbnail',
            field=models.FileField(default=None, upload_to=b''),
            preserve_default=False,
        ),
    ]
