# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20170624_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonegroup',
            name='file',
            field=models.FileField(upload_to=resources.models.generate_bone_group_filename_js),
        ),
    ]
