# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20170624_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoneGroupCategoryPair',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='bonegroup',
            name='categories',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
