# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import resources.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_pose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('thumbnail', models.FileField(upload_to=resources.models.generate_filename_png)),
                ('file', models.FileField(upload_to=resources.models.generate_preset_filename_js)),
            ],
        ),
    ]
