# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='license',
            field=models.CharField(choices=[('CC0', 'Creative Commons - Public Domain Dedication'), ('CC BY', 'Creative Commons - Attribution'), ('CC BY-SA', 'Creative Commons - Attribution - Share Alike'), ('CC BY-ND', 'Creative Commons - Attribution - No Derivatives'), ('CC BY-NC', 'Creative Commons - Attribution - Non-Commercial'), ('CC BY-NC-SA', 'Creative Commons - Attribution - Non-Commercial - Share Alike'), ('CC BY-NC-ND', 'Creative Commons - Attribution - Non-Commercial - No Derivatives')], default='CC BY', max_length=14),
        ),
        migrations.AddField(
            model_name='asset',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonegroup',
            name='license',
            field=models.CharField(choices=[('CC0', 'Creative Commons - Public Domain Dedication'), ('CC BY', 'Creative Commons - Attribution'), ('CC BY-SA', 'Creative Commons - Attribution - Share Alike'), ('CC BY-ND', 'Creative Commons - Attribution - No Derivatives'), ('CC BY-NC', 'Creative Commons - Attribution - Non-Commercial'), ('CC BY-NC-SA', 'Creative Commons - Attribution - Non-Commercial - Share Alike'), ('CC BY-NC-ND', 'Creative Commons - Attribution - Non-Commercial - No Derivatives')], default='CC BY', max_length=14),
        ),
        migrations.AddField(
            model_name='bonegroup',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pose',
            name='license',
            field=models.CharField(choices=[('CC0', 'Creative Commons - Public Domain Dedication'), ('CC BY', 'Creative Commons - Attribution'), ('CC BY-SA', 'Creative Commons - Attribution - Share Alike'), ('CC BY-ND', 'Creative Commons - Attribution - No Derivatives'), ('CC BY-NC', 'Creative Commons - Attribution - Non-Commercial'), ('CC BY-NC-SA', 'Creative Commons - Attribution - Non-Commercial - Share Alike'), ('CC BY-NC-ND', 'Creative Commons - Attribution - Non-Commercial - No Derivatives')], default='CC BY', max_length=14),
        ),
        migrations.AddField(
            model_name='pose',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preset',
            name='license',
            field=models.CharField(choices=[('CC0', 'Creative Commons - Public Domain Dedication'), ('CC BY', 'Creative Commons - Attribution'), ('CC BY-SA', 'Creative Commons - Attribution - Share Alike'), ('CC BY-ND', 'Creative Commons - Attribution - No Derivatives'), ('CC BY-NC', 'Creative Commons - Attribution - Non-Commercial'), ('CC BY-NC-SA', 'Creative Commons - Attribution - Non-Commercial - Share Alike'), ('CC BY-NC-ND', 'Creative Commons - Attribution - Non-Commercial - No Derivatives')], default='CC BY', max_length=14),
        ),
        migrations.AddField(
            model_name='preset',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
