# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accepted_terms',
            field=models.NullBooleanField(),
        ),
    ]
