# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_auto_20170825_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='author',
            field=models.CharField(max_length=30),
        ),
    ]
