# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20170825_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='category',
            field=models.CharField(default='full', max_length=30),
        ),
    ]
