# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resources.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0019_auto_20171003_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetForProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.CharField(default='unknown', max_length=30)),
                ('mesh', models.FileField(null=True, upload_to=resources.models.generate_processing_filename_stl)),
                ('license', models.CharField(choices=[('CC0', 'Creative Commons - Public Domain Dedication'), ('CC BY', 'Creative Commons - Attribution'), ('CC BY-SA', 'Creative Commons - Attribution - Share Alike'), ('CC BY-ND', 'Creative Commons - Attribution - No Derivatives'), ('CC BY-NC', 'Creative Commons - Attribution - Non-Commercial'), ('CC BY-NC-SA', 'Creative Commons - Attribution - Non-Commercial - Share Alike'), ('CC BY-NC-ND', 'Creative Commons - Attribution - Non-Commercial - No Derivatives')], default='CC BY', max_length=14)),
                ('rigid', models.BooleanField(default=True)),
                ('attachToGroup', models.CharField(max_length=30)),
                ('attachToBone', models.CharField(max_length=30)),
                ('px', models.FloatField()),
                ('py', models.FloatField()),
                ('pz', models.FloatField()),
                ('rx', models.FloatField()),
                ('ry', models.FloatField()),
                ('rz', models.FloatField()),
                ('sx', models.FloatField()),
                ('sy', models.FloatField()),
                ('sz', models.FloatField()),
                ('processing_started', models.DateField()),
                ('processing_finished', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('processing', 'processing'), ('complete', 'complete'), ('error', 'error')], default='waiting', max_length=14)),
                ('message', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
