# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_auto_20171111_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetforprocessing',
            name='sx',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='assetforprocessing',
            name='sy',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='assetforprocessing',
            name='sz',
            field=models.FloatField(default=1.0),
        ),
    ]
