# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_auto_20171111_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetforprocessing',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assetforprocessing',
            name='processing_finished',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetforprocessing',
            name='processing_started',
            field=models.DateField(blank=True),
        ),
    ]
