# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_auto_20171111_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetforprocessing',
            name='processing_finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='assetforprocessing',
            name='processing_started',
            field=models.DateField(null=True),
        ),
    ]
