# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_auto_20171111_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
