# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_asset_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetforprocessing',
            name='mesh',
            field=models.FileField(null=True, upload_to=resources.models.generate_processing_filename_obj),
        ),
    ]
